### PR TITLE
issue number 61. com.openfaas.scale.max and com.openfaas.scale.min ha…

### PR DESCRIPTION
**Pull request by hxalid**
https://github.com/hashicorp/faas-nomad/issues/61

### CODE REVIEW

**Comment by acornies** [comment]
Although, now I see that there might be an issue with propagating the invocation count in this call, but that's technically a separate issue.

**Comment by nicholasjackson** [comment]
Looks like Go-Releaser has updated the config format, let me pin this to a branch for an older version, once we merge this I will upgrade it.

**Comment by nicholasjackson** [comment]
@hxalid I have fixed the config and your PR is now building, had to move it to here: https://github.com/hashicorp/faas-nomad/pull/63

However if you are happy I can merge this and release an update later today.

Nic

**Comment by hxalid** [comment]
@nicholasjackson thank you for fixing the config issue. 

Sure, please feel free to merge it. 

Regards,
Khalid

**Pull request merged**
