### PR TITLE
basic auth + vagrant environment for integration testing

### PR DESCRIPTION
**Pull request by acornies**
- add Vagrantfile with saltstack provisioner and supporting files
- support for both virtualbox and vmware_fusion providers
- moved provisioning scripts into provisioning folder
- added nomad files for running with all-in-one environment

Addresses: #43 

Signed-off-by: Andrew Cornies <acornies@gmail.com>

### CODE REVIEW

**Comment by alexellis** [comment]
Do you have support for the KVM provisioner? I could try this on Linux if so.

**Comment by acornies** [comment]
Hi @alexellis I'll need to pull together a Linux host w/ Vagrant to test the libvirt provider reliably. Need another day or two.

**Comment by acornies** [comment]
Added basic auth to this PR which should address: #47

**Comment by acornies** [comment]
@alexellis I've added libvirt provider configuration to the Vagrantfile. If you can give it a go (assuming you have done the [installation steps](https://github.com/vagrant-libvirt/vagrant-libvirt#installation) on your Linux host) that would be great. We might have to tweak what interface the provider uses for the private ip, but other than that, there should be no other modifications to the Vagrantfile to support KVM.

**Pull request merged**
