### PR TITLE
[WIP] Issue 25

### PR DESCRIPTION
**Pull request by cpitkin**
@nicholasjackson @acornies Can I get a check of my implementation. The implementation details are in Issue #25. I am having an issue setting up the tests to work with the new format. If either of you could make some suggestions on where I am going wrong that would be great.

### CODE REVIEW

**Comment by cpitkin** [comment]
I also just noticed I need to squash and rebase. I'll do that here in the next day or so.

**Comment by acornies** [comment]
Looks like this is still unfinished? Should probably not open a PR unless `make test` runs successfully on your machine (and tests aren't commented out). I suggest if you want a review of your implementation, provide a link to your fork/branch etc. before PR.

**Comment by acornies** [comment]
Hi @cpitkin , I've opened #56 which should supersede this one. I needed to tackle this for my company's dev environment as well as use the agent's configured DC instead of static `dc1`. Thanks for the understanding.

**Comment by cpitkin** [comment]
@acornies No worries. Thanks for making the update.

**Pull request closed without merging**
