### PR TITLE
Add /system/info endpoint for faas-nomad

### PR DESCRIPTION
**Pull request by alexellis**
The purpose of this change is to make faas-nomad compatible with the
latest version of the API Gateway in OpenFaaS. Each provider should
be able to advertise the underlying provider and the version of the
code. A new version of faas-provider (0.6) is vendored into the repo
which brings in an optional health endpoint (turned off by default).
The version is being passed to the provider from main.go.

A subsequent change should implement the health endpoint.

A unit test was added for the info endpoint using the format found
for the other endpoints.

The advertised information in /system/info will be consumed by the
API gateway and logged for help debugging issues. It can also be
used to turn on/off UI features such as the "network" field which
does not make sense for all providers.

Signed-off-by: Alex Ellis (VMware) <alexellis2@gmail.com>

## Other comments

Nic this was tested via unit tests which I think prove the behavior works as expected, but not through bringing up a nomad environment. Please could you give it a run-through before or after merging?

### CODE REVIEW

**Comment by alexellis** [comment]
`go build` and `go test ./handlers` works fine but it looks like there is an issue in the CI pipeline.

`goreleaser: error: unknown short flag '-s', try --help`

(^ That is likely unrelated to the PR.)

**Comment by alexellis** [comment]
Bump

**Comment by nicholasjackson** [comment]
Sorry will check this tomorrow

**Comment by alexellis** [comment]
Awesome, thank you Nic!

**Pull request merged**
